apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
data:
  PRICING_URL: "http://pricing-svc:3000/price"
  INVENTORY_URL: "http://inventory-svc:3001/stock"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: docker.io/library/checkout:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: checkout-config
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-svc
  labels:
    app: checkout
spec:
  selector:
    app: checkout
  ports:
  - port: 3002
    targetPort: 3002